#Notes on Panda

In [1]:
#Import panda
import numpy as np
import pandas as pd

##Basic data structures in pandas
###Two types of classes:
1. Series: one-dimensional labeled array holding data of any type
   (e.g., integers, strings)
2. DataFrame: two-dimensional data structure that holds data like a twodimension array/table with rows and columns

##Object creation

In [ ]:
#Create a Series:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [ ]:
#Create a DataFrame
#passing a NumPy array with a datetime index using date_range() and labeled columns:
dates = pd.date_range("20130101", periods=6)
dates

df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2013-01-01 -1.246939 -0.420959  0.314771  0.965184
2013-01-02  0.180827 -0.206650  1.527734  0.237734
2013-01-03  0.975677 -1.301205 -0.344225  0.035156
2013-01-04  0.418868  0.199839 -0.599991  1.186771
2013-01-05 -0.272075 -1.196234  0.134393 -0.007392
2013-01-06  0.666291  0.317054  1.656307  0.055777

In [8]:
#Create a DataFrame
#passing a dictionary of objects where the keys are the column labels and the values are the column values
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
print(df2)

df2.dtypes

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

##Viewing data

In [10]:
#use DataFrame.head() and DataFrame.tail() to view the top and bottom rows of the frame:
print(df.head())

df.tail(3)

                   A         B         C         D
2013-01-01 -1.246939 -0.420959  0.314771  0.965184
2013-01-02  0.180827 -0.206650  1.527734  0.237734
2013-01-03  0.975677 -1.301205 -0.344225  0.035156
2013-01-04  0.418868  0.199839 -0.599991  1.186771
2013-01-05 -0.272075 -1.196234  0.134393 -0.007392

                   A         B         C         D
2013-01-04  0.418868  0.199839 -0.599991  1.186771
2013-01-05 -0.272075 -1.196234  0.134393 -0.007392
2013-01-06  0.666291  0.317054  1.656307  0.055777

In [12]:
#display DataFrame.index or DataFrame.columns
print(df.index)
print(df.columns)

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
Index(['A', 'B', 'C', 'D'], dtype='object')

In [13]:
#return NumPy representation of underlying data with DataFrame.to_numpy() without index or column labels
df.to_numpy()

array([[-1.24693906, -0.42095858,  0.31477107,  0.96518365],
       [ 0.18082678, -0.2066498 ,  1.52773426,  0.23773404],
       [ 0.97567711, -1.30120451, -0.34422472,  0.03515599],
       [ 0.41886799,  0.19983851, -0.59999119,  1.18677103],
       [-0.27207473, -1.19623446,  0.13439319, -0.00739186],
       [ 0.66629074,  0.31705359,  1.65630713,  0.05577652]])

In [14]:
#quick statistic summary of your data with describe()
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.120441 -0.434693  0.448165  0.412205
std    0.793206  0.685672  0.945287  0.525632
min   -1.246939 -1.301205 -0.599991 -0.007392
25%   -0.158849 -1.002415 -0.224570  0.040311
50%    0.299847 -0.313804  0.224582  0.146755
75%    0.604435  0.098216  1.224493  0.783321
max    0.975677  0.317054  1.656307  1.186771

In [15]:
#transpose data
df.T

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -1.246939    0.180827    0.975677    0.418868   -0.272075    0.666291
B   -0.420959   -0.206650   -1.301205    0.199839   -1.196234    0.317054
C    0.314771    1.527734   -0.344225   -0.599991    0.134393    1.656307
D    0.965184    0.237734    0.035156    1.186771   -0.007392    0.055777

In [ ]:
#sort by an axis: DataFrame.sort_index()
df.sort_index(axis=1, ascending=False)

                   D         C         B         A
2013-01-01  0.965184  0.314771 -0.420959 -1.246939
2013-01-02  0.237734  1.527734 -0.206650  0.180827
2013-01-03  0.035156 -0.344225 -1.301205  0.975677
2013-01-04  1.186771 -0.599991  0.199839  0.418868
2013-01-05 -0.007392  0.134393 -1.196234 -0.272075
2013-01-06  0.055777  1.656307  0.317054  0.666291

In [17]:
#sort by values: DataFrame.sort_values()
df.sort_values(by="B")

                   A         B         C         D
2013-01-03  0.975677 -1.301205 -0.344225  0.035156
2013-01-05 -0.272075 -1.196234  0.134393 -0.007392
2013-01-01 -1.246939 -0.420959  0.314771  0.965184
2013-01-02  0.180827 -0.206650  1.527734  0.237734
2013-01-04  0.418868  0.199839 -0.599991  1.186771
2013-01-06  0.666291  0.317054  1.656307  0.055777

## Selection
Optimised pandas data access methods:
- DataFrame.at()
- DataFrame.iat()
- DataFrame.loc()
- DataFrame.iloc()

## Getitem([])

##

In [18]:
#for a DataFrame, passing a single label selects a column and yields a Series
df["A"]

2013-01-01   -1.246939
2013-01-02    0.180827
2013-01-03    0.975677
2013-01-04    0.418868
2013-01-05   -0.272075
2013-01-06    0.666291
Freq: D, Name: A, dtype: float64

In [19]:
#alternatively, use the column name attribute
df.A

2013-01-01   -1.246939
2013-01-02    0.180827
2013-01-03    0.975677
2013-01-04    0.418868
2013-01-05   -0.272075
2013-01-06    0.666291
Freq: D, Name: A, dtype: float64

In [20]:
#passing a list of column labels selects multiple columns
df[["B", "A"]]

                   B         A
2013-01-01 -0.420959 -1.246939
2013-01-02 -0.206650  0.180827
2013-01-03 -1.301205  0.975677
2013-01-04  0.199839  0.418868
2013-01-05 -1.196234 -0.272075
2013-01-06  0.317054  0.666291

In [22]:
#select matching rows with ":"
print(df[0:3])

print(df["20130102":"20130104"])

                   A         B         C         D
2013-01-01 -1.246939 -0.420959  0.314771  0.965184
2013-01-02  0.180827 -0.206650  1.527734  0.237734
2013-01-03  0.975677 -1.301205 -0.344225  0.035156
                   A         B         C         D
2013-01-02  0.180827 -0.206650  1.527734  0.237734
2013-01-03  0.975677 -1.301205 -0.344225  0.035156
2013-01-04  0.418868  0.199839 -0.599991  1.186771